### ISSUE TITLE
escrow smart contract

### ISSUE THREAD

**Issue by seichris** [seichris/bounty-issues#3]
### Flow:

1. funder funds an issue
2. second funder funds the same issue
3. developer solves issue and requests payout
4a. funder allows payout
4b. fund does not allow payout, and judge decides on payout

### Questions:

- can we reuse octobay's contracts? Other templates?
- if we offer projects to use our escrow contract, how to set a project judge?
-

**Comment by dohaki** [comment]
Maybe something like this makes sense https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/payment/escrow/RefundEscrow.sol?

**Comment by seichris** [comment]
the contract should allow for

1. funder 1 funds the issue
2. funder 2 funds the issue
3. funder 3 funds the issue
4. funder 3 ragequits his funds
5. developer 1 commits to solving the issue, in certain time frame
6. developer 2 commits to helping for 50% of the funds
a. developers finish > payout 50/50 to each dev
b. developer 1 finishes > payout 100%
c. developers fail > payback to funders
d. everyone is angry > repo admin as judge decides over funds
